### ISSUE TITLE
https support instead of ssh protocol

### ISSUE THREAD

**Issue by gaborbernat** [asottile/all-repos#101]
Currently, some things break if someone specifies http urls for repos (). Notably the fork operation for push.

**Comment by asottile** [comment]
indeed, this bit currently assumes ssh urls: https://github.com/asottile/all-repos/blob/f7622444c746175af094214932725e642713e7b5/all_repos/push/github_pull_request.py#L20

Can an automated push happen over non-ssh protocols? 🤔

**Comment by gaborbernat** [comment]
Yes 👍 I would expect the code checks the type of remote it has and uses that protocol.
