### ISSUE TITLE
using keyring as credential source

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/all-repos#107]
while investigating putting a all_repos configuration into a git repo, i noted that credentials couldn't be externalized 

so more than one person wouldnt be able to use it
this could b elevated by having supportt for fetching api keys/passwords from keyring

**Comment by asottile** [comment]
Ideally I'd rather not make the credentials part more complicated than it needs to be --one solution that I've seen work with this is to use an external wrapper script to generate the configuration with the proper credential store.

the credentials are only needed during clone / push so a read-only copy can be used in a mult-tenant system

**Comment by RonnyPfannschmidt** [comment]
@asottile if credentials could be passed in via cli/env that would work as well

**Comment by asottile** [comment]
what's so hard about writing a json file?

**Comment by RonnyPfannschmidt** [comment]
I'd like to avoid any setup that can end with credentials being accidentally committed to an git repo, writing credentials to files is trivial, protecting the files is not trivial

**Comment by asottile** [comment]
`.gitignore`, git hooks (pre-commit / pre-receive), tests are all pretty solid defenses 🤷‍♂ 

I'd like to punt on this as there's way too many credential stores and I think I've picked a pretty reasonable lowest common denominator that someone can write a little bit of glue to populate

**Comment by jrarmstro** [comment]
+1 for exposing a CLI parameter or some other way to define the API token. I'd like to automate this to work in our CI system but can't right now because that necessitates writing the credentials to disk.

**Comment by RonnyPfannschmidt** [comment]
@asottile what about making

1. something to declare shared settings (atm i have to put a api key under the same name for both pull and push settings, when using a custom gitlab even more)

2. having obtained settings and having a entrypoint to configure them

a config would look like
```json

{
    "output_dir": "checkouts",
    "source": "all_repos.source.gitlab_org",
    "all_branches": true,
    "shared_settings": {
        "api_key": {
            "@from": "env",
            "name": "INTERNAL_GITLAB_APIKEY"
        },

        "base_url": "https://gitlab.cee.internal.org.example.com/api/v4"
    },

    "source_settings":  {
        "org": "myproject-qe",
    },
    "push": "all_repos.push.gitlab_pull_request",
    "push_settings": {
        "fork": false
    }
}```

and plugins not under all-repos could add extra sources like vault, keyring

**Comment by asottile** [comment]
> but can't right now

surely you can read your credential store and write out the configuration file

**Comment by jrarmstro** [comment]
> > but can't right now
> 
> surely you can read your credential store and write out the configuration file

The issue here is that writing the credentials to disk at any point in time is unacceptable for my use case. I can write source/push modules to resolve from the environment, but would prefer to know if such a PR would be accepted before making the effort.

**Comment by asottile** [comment]
> that writing the credentials to disk at any point in time is unacceptable for my use case

I'm sorry, I don't understand, could you elaborate?  you realize if you're cloning with credentials those'll end up on disk right?

**Comment by jrarmstro** [comment]
> I'm sorry, I don't understand, could you elaborate? you realize if you're cloning with credentials those'll end up on disk right?

I'm failing to find these credentials on disk. At the very least it would be nice to be able to resolve the `push` credentials so that we can properly secure and scope write access.

**Comment by asottile** [comment]
@jrarmstro why can't you write a json file?

**Comment by asottile** [comment]
please just answer the question

**Comment by jrarmstro** [comment]
We can't write a json file because writing these credentials to disk in a CI environment would be an enormous security risk.

**Comment by asottile** [comment]
> writing these credentials to disk in a CI environment would be an enormous security risk.

please explain.  don't try and push your opinions with fear.  have concrete reasons for the claims you're making.  demonstrate

**Comment by jrarmstro** [comment]
We've opted to create our own `source` and `push` modules.
