### ISSUE TITLE
Cloning fails due to authentication error

### ISSUE THREAD

**Issue by CodingSpiderFox** [asottile/all-repos#119]
I get errors on all my repos, even the public ones when running

`all-repos-clone --config-filename all-repos.json --jobs 1`

My config is 

```
{
    "output_dir": "output",
    "source": "all_repos.source.github",
    "source_settings":  {
        "api_key": "hexadecimal-stuff-from-github-settings-page",
        "username": "CodingSpiderFox"
    },
    "include": "",
    "exclude": "^(gecko-dev)$",
    "push": "all_repos.push.github_pull_request",
    "push_settings": {
        "api_key": "hexadecimal-stuff-from-github-settings-page",
        "username": "CodingSpiderFox"
    }
}
```

Example error output is:

```
Initializing CodingSpiderFox/maintenance-tools
Initialized empty Git repository in /home/user/gitrepos/output/CodingSpiderFox/maintenance-tools/.git/
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error fetching output/CodingSpiderFox/acx100-acx-mac80211
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error fetching output/CodingSpiderFox/ardour-sessionparser
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by asottile** [comment]
sounds like you don't have your ssh keys set up?

does this work outside of `all-repos`?

```bash
git clone git@github.com:CodingSpiderFox/ardour-sessionparser
```

**Comment by CodingSpiderFox** [comment]
I was thinking about that it might require an SSH key but either the documentation is not clear that this is a necessary precondition or I overlooked it

Where do I need to put the private key?

**Comment by asottile** [comment]
how do you normally clone repositories?

this has directions for setting up ssh keys -- generally they are more secure than cloning over https (I assume that's how you're currently cloning ?): https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by CodingSpiderFox** [comment]
I used to do it over HTTPS with the API Token before

**Comment by CodingSpiderFox** [comment]
OK, I found out how to do it

`eval "$(ssh-agent -s)"` (start ssh agent)
`ssh-add ~/.ssh/id_rsa` (add private key to ssh-agent)

**Comment by asottile** [comment]
sweet -- cloning over ssh is generally seen as more secure than typing in passwords and keeping authentication tokens on disk so it was kind of assumed to be the way repositories would get cloned

**Comment by CodingSpiderFox** [comment]
Thanks for the advice :)

**Comment by domportera** [comment]
Hey I'm having this issue too, but with bitbucket. Here's my config:

`{
    "output_dir": "E:\\Repo Backups",
    "source": "all_repos.source.bitbucket",
    "source_settings":  {
        "app_password": "bitbucket's generated app password",
        "username": "domFC"
    },
    "push": "all_repos.push.readonly",
    "push_settings": {},
    "all_branches": true
}`

any advice? I tried setting up SSH but it doesnt seem that the bitbucket source is primed to use that based on the documentation

**Comment by asottile** [comment]
show your error

**Comment by domportera** [comment]
sorry just thought to fetch that 
![image](https://user-images.githubusercontent.com/6530600/162495110-7c431238-f7db-4343-83cc-e098a4f36f85.png)

**Comment by asottile** [comment]
please don't post screenshots of text -- they are (1) unreadable (2) cannot be viewed in my contrast settings (3) unsearchable

but also that error message indicates your ssh key is not set up properly

**Comment by domportera** [comment]
sorry I wouldnt have but im running an old version of windows where I can't select text in the command line, let alone copy and paste /:

but thank you for the tip. im new to SSH (havent used it before this tool) so i'll work on that. Is there anywhere in the config I need to specify SSH information or is it all external to the tool? sorry for a dumb question

**Comment by asottile** [comment]
nope that's not the problem -- you probably forgot to authorize your key to your account on the bitbucket side?

**Comment by domportera** [comment]
I definitely did it on the bitbucket side, but I'm troubleshooting using their [troubleshooting page](https://support.atlassian.com/bitbucket-cloud/docs/troubleshoot-ssh-issues/#Could-not-open-a-connection-to-your-authentication-agent). I'll report back when I solve it if you want, though it may not be relevant to all-repos

**Comment by domportera** [comment]
## Fixed!
I fixed it, very dumb move on my end and totally irrelevant for you so sorry to bother! But in case anyone else is new to SSH for the sake of this amazing tool, here was the issue:

I didn't save my SSH keys to the default directory (~/.ssh) with the default names (id_rsa & id_rsa.pub). I didn't see any warnings regarding this in the set-up instructions I was following, but it turns out it's critical for authentication to persist between ssh-agent processes.

Thank you for making this by the way, it's a total life saver and an absolute public good. and I appreciate your patience!
