### ISSUE TITLE
Allow comments in config files

### ISSUE THREAD

**Issue by sloria** [asottile/all-repos#131]
I know people have strong opinions about config formats. I don't. json5, toml, yaml--all are fine with me, as long as I can add comments 😄

**Comment by asottile** [comment]
changing the config language is a breaking change and I'm not happy with the other formats (json5 does not have a good parser in python, I'm planning to write one eventually once I learn more about making parsers correctly)

you can do this as a hack iirc:

```json
{
    "#comment": "...".
    "actual_thing": "..."
}
```

**Comment by sloria** [comment]
The hack works but doesn't doesn't have the same visual weight that comments do.

This isn't urgent at all--I'll probably just wait for json5.

**Comment by asottile** [comment]
cool, going to close this for now since there's no plan to actively work on it
