### ISSUE TITLE
Cloning does not work for GitHub Enterprise installations with custom domain

### ISSUE THREAD

**Issue by akshaykumar90** [asottile/all-repos#133]
Looks like `github.com` is hardcoded in the repo url:

https://github.com/asottile/all-repos/blob/651ab491d1c3a799f677c107c2edde561364c013/all_repos/github_api.py#L52

I could get the command to work by changing this to my custom domain name.

Am I doing something wrong? We should add an option to allow setting this?

**Comment by asottile** [comment]
huh yeah weird -- it's ~supposed to take on this value but I guess it never got actually used? https://github.com/asottile/all-repos/blob/651ab491d1c3a799f677c107c2edde561364c013/all_repos/source/github.py#L14

**Comment by asottile** [comment]
(I also no longer have access to an enterprise instance after layoffs 😭)

**Comment by akshaykumar90** [comment]
I am sorry to hear that. :(

The `base_url` part is expected to be set to `https://{your_domain}/api/v3`. I think we can just extract the hostname from this url and use that here instead?

Or just expose this as its own config option?

**Comment by asottile** [comment]
whatever works!
