### ISSUE TITLE
sed -i needs an extension on osx

### ISSUE THREAD

**Issue by davidszotten** [asottile/all-repos#137]
`'sed -i s/HAI/BAI/g'` fails on os x (bsd sed). there it needs to be `'sed -i '' s/HAI/BAI/g'`

(noticed because it makes the test suite fail on os x)

**Comment by asottile** [comment]
please [read the docs](https://github.com/asottile/all-repos#all-repos-sed-options-expression-filenames)

**Comment by davidszotten** [comment]
could we consider detecting os x (or bsd sed) when running the test suite and skipping instead?

**Comment by asottile** [comment]
I think a failing test is appropriate in this situation as that sed is not supported as documented in the README

**Comment by davidszotten** [comment]
ok
