### ISSUE TITLE
Thoughts on the current documentation

### ISSUE THREAD

**Issue by jugmac00** [asottile/all-repos#140]
While `all-repos` is now a tool I do not want to miss anymore, >>I<< had a bit of a hard time to wrap my head around it at first.

From our Twitter conversation I sensed that from your perspective the documentation is sufficient.

These are some suggestions from my side, which would have helped me **a lot** when I started using `all-repos`.

At least it is no longer a "I missed something in your documentation", but some concrete things :-)

If you find something useful, I'd volunteer to create a pull request. If you do not like the suggestions, I am fine when you close the issue.

a) While the tagline(Clone all your repositories and apply sweeping changes.) is concise and on the point, I would add another paragraph to give a high level overview what the user can expect.

e.g. something like this

> `all-repos` really shines when you have to manage a lot of git repositories. It offers command line tools to clone all of your repositories at once, supports you in finding files or text within those repositories, and as a highlight, even lets you do changes across all repositories and automatically creates pull requests for you.

b) While you stated that a step by step guide does not make a lot of sense as everyone's setup is different, at least there are some common steps:

- pip install all-repos
- create a configuration
- clone some repositories
- act on them
  - read only
  - with modifications and possible automatically create pull requests

The current documentation jumps from the installation directly to the CLI reference.

I would possibly unite the first three steps as "preparations" or "setup", and then lead over to the "actions".

When introducing the two kinds of actions (read only vs with modification), I would mention, that for the latter to make really sense you need to configure a push module, and explicitly mention, that with executing an autofixer, branches, commits and pull requests get created automatically.

c) speaking of the configuration, while the error messages are obvious, it would not hurt to add that the configuration file
- should not be readable for groups / others (chmod 0600)
- should be called `all-repos.json` so the `all-repos` commands automatically pick it up (you mention it elsewhere, but not in the [configuring section](https://github.com/asottile/all-repos#configuring))

d) Loosely following the documentation categories of https://www.writethedocs.org/videos/eu/2017/the-four-kinds-of-documentation-and-why-you-need-to-understand-what-they-are-daniele-procida/

- the current documentation is a reference
- my above suggestions corresponds to a "tutorial" or an introduction
- then maybe adding one or two use-cases would be great?

A use-case could be (from my past experience):
- update the Python version in all travis files from `3.9-dev` to `3.9`
https://github.com/jugmac00/til/blob/master/zope/how-to-update-all-zopefoundation-repositories-at-once.md
- find out which repositories use macOS builds
- update a badge URL in all repos

P.S.: I'll update the blog post in a second - sorry for the non-constructive criticism

**Comment by asottile** [comment]
tbh, I don't think much needs to change here, I know of hundreds of people that have set this up with the current set of documentation without issue or question

(a) I don't think a longer description adds anything
(b) maybe a "quick start" is fine, but the rest of it should be obvious, you configure a particular type of pusher it's going to happen when you run an autofixer (some of the pushers don't do pushes as well).  it should be fairly obvious that a thing called a "fixer" is going to make changes, I don't think it needs to be said (even though it already is)
(c) this isn't correct, the configuration file can be named anything (and there's a `--config` option) and the mode is only a requirement on non-windows.  I'd rather lean on the error messages in the implementation than documentation implementation details that can get out of date
(d) there's https://github.com/asottile/all-repos-incantations already though I haven't updated it in quite a while

so at most a small tutorial, but again I don't think it's possible to write a universally helpful tutorial because every setup is different (that's why every piece is pluggable)

**Comment by hugovk** [comment]
A small tutorial would be good, and agree it doesn't need to be universal (and that's probably not possible).

The current documentation is thorough and a very good reference guide: I went through the blogpost, and then it was very useful to look up options in the docs to see what they do and customise things.

**Comment by jugmac00** [comment]
> tbh, I don't think much needs to change here, I know of hundreds of people that have set this up with the current set of documentation without issue or question

![300](https://user-images.githubusercontent.com/9895620/98082443-06451980-1e79-11eb-8f87-66b2f40aba73.png)

Ok, I am convinced! :-)

> (d) there's https://github.com/asottile/all-repos-incantations already though I haven't updated it in quite a while

This is a great list and should be linked from the README here. What do you think? Maybe directly after the tutorial a la "Now that you know how to get started, here are some more ideas what to do with `all-repos`.

> so at most a small tutorial, but again I don't think it's possible to write a universally helpful tutorial because every setup is different (that's why every piece is pluggable)

True. Maybe exactly because of that I'd still think a longer description at the top, which would give a general overview, would be a good idea. But the 300 have spoken :-)
