### ISSUE TITLE
How would I use this to clone/update/pull all starred repos?

### ISSUE THREAD

**Issue by cocoonkid** [asottile/all-repos#141]
How would I use this to clone/update/pull all starred repos?

curl -I https://api.github.com/users/$user/starred 

Thanks in advance

**Comment by asottile** [comment]
you would write [a `source`](https://github.com/asottile/all-repos#writing-your-own-source) similar to the [existing ones](https://github.com/asottile/all-repos/tree/master/all_repos/source) -- you can probably use [this one](https://github.com/asottile/all-repos/blob/master/all_repos/source/github_org.py) as a guide

if you want, you could also write a few tests and submit it as a pull request!

**Comment by cocoonkid** [comment]
Added to my todos :smile:
