### ISSUE TITLE
make clone removals interactive

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/all-repos#147]
while messing around with recreating a gitlab_org source i did put my all-repos checkout into the target dir for a all-repos clone, it was fabulously destroyed

**Comment by asottile** [comment]
I don't think interactive is the correct choice, but perhaps failing if something unexpected there is better?  `all-repos-clone` is intended to be cron-able

**Comment by RonnyPfannschmidt** [comment]
I'm trying to use it to sync all repos i interact with to a folder

**Comment by RonnyPfannschmidt** [comment]
@asottile would a opt-in/opt out be a viable option?

**Comment by asottile** [comment]
I believe all-repos has enough information to add/remove just the repositories it maintains (read the repos list before, diff with after, add/remove the ones it manages)

and then all that's left is to error if the directory already exists and contains things that would be managed that aren't already

**Comment by RonnyPfannschmidt** [comment]
@asottile so that means all-repos-clonse is not suitable to clone repos one intends to work with manually in detail as a server change could drop them?

**Comment by asottile** [comment]
yeah it's not really meant as a development environment, or at least that's not how I use it -- I could see it maybe as a way to seed the environment (and then discard the all-repos part of it) maybe?

the way I set up my work environment:

```
~/
--> workspace/
--> --> all-repos/
--> --> --> repos/ (managed by all-repos, read-only)
--> --> (other repositories, cloned and deleted when I'm done working on them)
```

**Comment by RonnyPfannschmidt** [comment]
@asottile thanks for the clarification, then a helper to fetch a specific repo for working on it may be just what i need
would it be reasonable to add a tool for managed checkouts

**Comment by asottile** [comment]
one thing that I use that works pretty well is `all-repos-complete` -- it adds tab completion for `git clone`

```
eval "$(all-repos-complete --bash)"
```

and then `git clone` `<tab>` -> `git clone git@github.com:`  `aso` `<tab>` -> `git clone git@github.com:asottile/` `do` `<tab>` -> `git clone git@github.com:asottile/dockerfile`

is that what you had in mind? or something else entirely

**Comment by RonnyPfannschmidt** [comment]
No, if I have all the clones already, I'd like to use them as starting point to speed things up

Alter naively just maintaining a mirror of bare repos

**Comment by asottile** [comment]
ah so essentially automating `git clone --reference path/to/all-repos/clone target`

**Comment by asottile** [comment]
err maybe `--shared` `--dissociate` or whatever the correct set of options is

**Comment by RonnyPfannschmidt** [comment]
closing as not actionable as it was requested
