### ISSUE TITLE
document if/how all_repos_clone repos can be used as full repos

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/all-repos#148]
i cloned a set of repos in a private organization using all-repos

i noted that im unable to fetch branches from origin

if i go in and use a new clone using the same remote, it works fine

as far as i understood, the primary difference is 
`fetch = +refs/heads/*:refs/remotes/origin/*` on self-clone vs `fetch = +refs/heads/master:refs/remotes/origin/master` in all-repos clone

**Comment by asottile** [comment]
this is documented, see [`all_branches`](https://github.com/asottile/all-repos#configuring)

**Comment by RonnyPfannschmidt** [comment]
That you for clarification, I completely missed that
