### ISSUE TITLE
Include pattern does not work.

### ISSUE THREAD

**Issue by CodingSpiderFox** [asottile/all-repos#153]
I use the following config for cloning my GitHub repos:

```
{
    "output_dir": "output",
    "source": "all_repos.source.github",
    "source_settings":  {
        "forks": true,
        "private": true,
        "archived": true,
        "api_key": ""
        "username": "CodingSpiderFox"
    },
    "include": "^z.*",
    "push": "all_repos.push.github_pull_request",
    "push_settings": {
        "api_key": "...",
        "username": "CodingSpiderFox"
    },
    "all_branches": true
}
```

I would have expected that all repos starting with "z" would be cloned. But not a single one gets cloned.

Here is an excerpt from the resulting repos.json.

`{"CodingSpiderFox/yara": "git@github.com:CodingSpiderFox/yara", "CodingSpiderFox/youtube-comment-suite": "git@github.com:CodingSpiderFox/youtube-comment-suite", "CodingSpiderFox/ytplaylistmanager": "git@github.com:CodingSpiderFox/ytplaylistmanager", "CodingSpiderFox/zfs": "git@github.com:CodingSpiderFox/zfs", "CodingSpiderFox/zfs-multi-mount": "git@github.com:CodingSpiderFox/zfs-multi-mount", "CodingSpiderFox/zfs-snap-diff": "git@github.com:CodingSpiderFox/zfs-snap-diff", "CodingSpiderFox/zfsbud": "git@github.com:CodingSpiderFox/zfsbud", "CodingSpiderFox/zfs_autobackup": "git@github.com:CodingSpiderFox/zfs_autobackup", "CodingSpiderFox/zinit": "git@github.com:CodingSpiderFox/zinit", "CodingSpiderFox/zplug": "git@github.com:CodingSpiderFox/zplug", "CodingSpiderFox/zsh-autopair": "git@github.com:CodingSpiderFox/zsh-autopair", "CodingSpiderFox/zsh-autosuggestions": "git@github.com:CodingSpiderFox/zsh-autosuggestions", "CodingSpiderFox/zsh-fast-alias-tips": "git@github.com:CodingSpiderFox/zsh-fast-alias-tips", "CodingSpiderFox/zsh-git-sync": "git@github.com:CodingSpiderFox/zsh-git-sync", "CodingSpiderFox/zsh-tmux-auto-title": "git@github.com:CodingSpiderFox/zsh-tmux-auto-title", "CodingSpiderFox/zsh-you-should-use": "git@github.com:CodingSpiderFox/zsh-you-should-use", "CodingSpiderFox/zsh-zsnapac": "git@github.com:CodingSpiderFox/zsh-zsnapac"}`

However, the repos_filtered.json stays empty.

**Comment by asottile** [comment]
I'm not sure why `^z.*` would match `CodingSpiderFox` -- did you mean `^CodingSpiderFox/z` ?

**Comment by CodingSpiderFox** [comment]
Yes, that's what I meant. I thought it would that all repos in my username and apply the include pattern only to those. 

So I would need to change it to "^CodingSpiderFox/z.*$" ?

**Comment by CodingSpiderFox** [comment]
Didn't mean to bother you but it's more efficient to ask than to try over and over again when you've been trying already for over an hour ;)
