### ISSUE TITLE
Branch name prefix is fixed

### ISSUE THREAD

**Issue by faph** [asottile/all-repos#158]
all-repos always adds a branch name prefix `all-repos_autofix_`. At work, we use a branch naming standard which doesn't "approve" of the prefix unfortunately.

Would there be any appetite for changing that behaviour? For example making the prefix configurable?

**Comment by asottile** [comment]
feel free to fork if you need a different prefix -- or better yet, add a special case to your work's thing which allows a separate prefix (or write your own `push` module which adjusts the branch naming)

also if your work is using my software I'd suggest they [sponsor](https://github.com/sponsors/asottile), especially if you want customized functionality

**Comment by asottile** [comment]
especially because your work is a trillion dollar company :P

**Comment by faph** [comment]
I would like to contribute with a PR and it feels changing at source, ie where the prefix is set seems sensible. But happy to do it in a custom push module too.
