### ISSUE TITLE
allow to setup multiple remotes

### ISSUE THREAD

**Issue by teto** [asottile/all-repos#161]
hi,

is it possible to configure the tool to setup several remotes for a same clone ? ideally with their names

**Comment by asottile** [comment]
nope, I don't see how that would work -- the source provides a 1:1 mapping between repository name and remote url

**Comment by teto** [comment]
in the json config, sthg like  `folder : { 'origin': github.com/upstream/repo, 'fork;  github.com/my/fork }`

**Comment by asottile** [comment]
the repositories are meant to be readonly, the `push` should take care of that -- it already has a fork option for this specific usecase
