### ISSUE TITLE
all-repos.json has too-permisive permissions 

### ISSUE THREAD

**Issue by ibLeDy** [asottile/all-repos#165]
When running it on Windows, I'm getting the following error:

```console
$ all-repos-clone
all-repos.json has too-permissive permissions, Expected 0o600, got 0o666
```

```console
$ ls -l all-repos.json
-rw-r--r-- 1 bLeDy 197609 377 Apr  9 17:34 all-repos.json
```

Windows: `Version 20H2 (OS Build 19042.906)`
Python: `3.9.1`
Pip: `21.0.1`
all-repos: `1.21.0`

**Comment by asottile** [comment]
yeah windows doesn't have the same concept of permissions -- https://github.com/asottile/all-repos/blob/5efc2a11324afa3a6fe8fac61ddc61ef252d5ba4/all_repos/config.py#L37-L43

needs something like this: https://github.com/asottile/scratch/blob/36580f3c752f3d66da5536695fcb1493d55efb15/python/git-github-fork#L22-L32

**Comment by AIGeneratedUsername** [comment]
I am sorry for touching an old thread with a question, but what is the point of checking file permissions? I just got this error on Linux for a manually created file. I can change file permissions, but I wonder what is the reason.
I hope a little note about this may be useful for someone who will want to contribute. Thanks.

**Comment by chriskuehl** [comment]
The config file typically has secret API tokens in it, so you should make sure it's not readable by other users. If you're on a single-user system (e.g. your laptop) then it's not as big of a concern as if you are working on a shared server where other people using the server could directly read your world-readable file, but it is still better to make it readable by only your user.
