### ISSUE TITLE
when git commiter email is not set commiting fails even if author is passed

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/all-repos#189]
i have a particular setup where i don't set the git user email for folders outside of specific directories in my home folder
(to control which commits go by my opensource mail and my work mail)

when i ran all-repos-sed without an author, it errors about the author, once i gave the author, it errors about the commit-er which cant be set

**Comment by asottile** [comment]
you can always `GIT_COMMITTER_EMAIL=...` I think ?

**Comment by RonnyPfannschmidt** [comment]
I want that out of the general environment however, adding only to all repo calls is a bit of a pain in any case

**Comment by RonnyPfannschmidt** [comment]
ok
