### ISSUE TITLE
Question: Is it possible to create PR against non-default branch?

### ISSUE THREAD

**Issue by noorul** [asottile/all-repos#220]

**Comment by noorul** [comment]
I thought it was a normal use case for which a solution could be part of the core. I thought we could add an optional config `default_branch` to override the one that is set by the forge.

**Comment by asottile** [comment]
no thanks -- it's not difficult for one to write a custom push with whatever behaviour they need meaning that the "core" doesn't need to carry the complexity of every uncommon possibility

**Comment by noorul** [comment]
@asottile I am not sure how can one override https://github.com/asottile/all-repos/blob/master/all_repos/clone.py#L64 in a custom source or push module. Or am I missing something? Can you please help me or guide me on how I can achieve these using custom modules?

**Comment by asottile** [comment]
that's for cloning, unrelated to the fixer or the push module

**Comment by noorul** [comment]
@asottile My question was also related to that. Maybe it is not clear. Let me explain it with an example.

Our forge is using the default branch as `mainline` for all the repositories. But our development happens on `devel` branch. So, in this case, the current clone implementation will use the `mainline` branch to apply auto fixers and PR will be created against the same.  I am looking for an option to override this behavior.

**Comment by asottile** [comment]
fixers and push modules are arbitrary code -- you can do whatever you want in there

**Comment by noorul** [comment]
@asottile But this will make the fixers a little complex and also the built-in commands `all-repos-grep`, `all-repos-sed`  and `all-repos-find-file` cannot be used.

**Comment by asottile** [comment]
tough? your self inflicted is causing you problems

stop at mentioning me
