### ISSUE TITLE
Setting output_dir to "." does rmtree to the current directory

### ISSUE THREAD

**Issue by AdamGagorik** [asottile/all-repos#252]
I noticed running `all-repos-clone` with a configuration similar to the one below will remove all files and directories in the current directory.

```json
{
    "output_dir": ".",
    "source": "all_repos.source.github_org",
    "source_settings":  {
        "api_key": "redacted",
        "private": true,
        "org": "example"
    },
    "push": "all_repos.push.github_pull_request",
    "push_settings": {
        "api_key": "redacted",
        "username": "FirstLast"
    },
    "include": "prefix.*"
}
```

It is clear now the intent is to have `output_dir` be something other than the current directory.  However, I think a check to prevent removing the current directory should be considered.

**Comment by asottile** [comment]
yeah `.` is kinda a bad decision there :P -- feel free to send a patch
