### ISSUE TITLE
Allow to specify post-pull and post-update hooks (shell scripts that run for every cloned project)

### ISSUE THREAD

**Issue by AIGeneratedUsername** [asottile/all-repos#265]
## What
Allow to specify post-pull and post-update hooks (shell scripts that run for every cloned project). Similar to what [cookiecutter allows to do](https://cookiecutter.readthedocs.io/en/stable/advanced/hooks.html). 

Hooks are for updating Git submodules, installing dependencies, etc. It is not about code modification and committing what "autofixers" already do.

## Current behavior

`all-repos-clone` has no support for post-pull or post-update hooks.

"autofixers" was looking promising, but after reviewing their source code, I found that they do commits and have no support to simply run a bash command :face_exhaling: 

## Syntax proposal

```bash
all-repos-clone --post_clone_hook_file path/to/post_hook_script.sh
```
For example, I would be very happy to run the following commands for every newly cloned repository: 
```sh
# my_post_pull_script
git submodule update --remote --init --recursive
poetry env use python3.10
poetry install
pre-commit install && pre-commit install --hook-type commit-msg
```

Or, an inline command:
```bash
all-repos-clone --post_clone_hook "git submodule update --remote --init --recursive"
```
```bash
all-repos-clone --post_update_hook "git submodule update --remote --recursive"
```

**Comment by asottile** [comment]
in the future, please describe the problem first rather than prescribing a solution -- you often fall into XY territory by not understanding the landscape

___

the clones aren't really meant to be used as development environments -- that said, you can do what you want

the commands are designed to be modular, for example:

```bash
all-repos-list-repos --output-paths | xargs --replace git -C {} submodule update --init
```
