### ISSUE TITLE
gitolite source

### ISSUE THREAD

**Issue by chriskuehl** [asottile/all-repos#27]
Hi friend :)

I'd like to add a gitolite source and wanted to run the approach by you before sending a PR. A couple questions:

1. For getting the list of repositories, seems like the only way provided via the gitolite API itself is [the `info` command](http://gitolite.com/gitolite/user/#the-info-command). It provides a handy `-json` flag, e.g.:
   ```
   $ ssh git@git.mycompany.com info -json
   {
      "repos" : {
         "a_repo" : {
            "perms" : {
               "W" : 1,
               "R" : 1
            }
         },
         "some_repo-DEPRECATED" : {
            "perms" : {
               # "W" key is omitted entirely
               "R" : 1
            }
         }
      }
      "gitolite_version" : "1.2.3",
      "USER" : "git@somehost",
      "GL_USER" : "ckuehl",
      "git_version" : "1.2.3"
   }
   ```

   Potentially we could provide other ways to get this list (e.g. something like y/gits), but I'm thinking if I wanted to do that, I'd just format that into a JSON file and use the JSON file source.

   So, does over SSH sound okay? And if so, do you prefer subprocessing out to ssh or using paramiko? (I think I prefer the subprocess approach just to avoid adding a new dep?)

2. Actually I guess I only had one question. This looks pretty straightforward to implement :P

**Comment by asottile** [comment]
ssh via `subprocess` seems good to me!
