### ISSUE TITLE
all-repos-clone wipes out pending changes without warning

### ISSUE THREAD

**Issue by pianofab** [asottile/all-repos#273]
Quoting from the docs:

> all-repos-clone [options]
> Clone all the repositories into the output_dir. If run again, this command will update existing repositories.

It sounds like it may be intended to be used also as "get latest"... however:

I simply edited a Pipfile and removed a Pipfile.lock (excerpt of all-repos-clone log below):

```
M       Pipfile
D       Pipfile.lock
Switched to branch 'master'
```

The clone operation switched to master and the other branch remained there, but when I switched back to it, git status (and git diff) came up empty.

If this is the intended behavior, it is a bit jarring.

For the time being, I set it up like so:

```json
{
    "output_dir": "kcos",
    "source": "all_repos.source.json_file",
    "source_settings": {
        "filename": "kcos-repos.json"
    },
    "push": "all_repos.push.readonly",
    "push_settings": {}
}
```

I have a bunch of our microrepos listed in kcos-repos.json, of course.

**Comment by asottile** [comment]
the all-repos output is not intended to be a development environment -- it's meant to be a readonly queryable / rewritable source
