### ISSUE TITLE
Support tilde in output_dir

### ISSUE THREAD

**Issue by kytta** [asottile/all-repos#274]
I have a single location for my output dir, that is independent of the machine I run `all-repos` on, my username, or config file location. To save time, I sync all-repos config across my machines and use `~` in the `output_dir` option:

```json
{
  "output_dir": "~/Code",
  "...": "..."
}
```

When I run all-repos, it fails with `FileNotFoundError: [Errno 2] No such file or directory: '<PATH_TO_CONFIG_DIR>/~/Code/repos_filtered.json'`

Perhaps we should add a check for the first character being a tilde and then using [`os.path.expanduser`](https://docs.python.org/3/library/os.path.html#os.path.expanduser)? For example:

```diff
def load_config(filename: str) -> Config:
    ...

-    output_dir = os.path.join(filename, '..', contents['output_dir'])
+    output_dir = contents['output_dir']
+    if output_dir.startswith('~'):
+        output_dir = os.path.expanduser(output_dir)
+    else:
+        output_dir = os.path.join(filename, '..', output_dir)
    output_dir = os.path.normpath(output_dir)
    
    ...
```

**Comment by asottile** [comment]
the path is intended to be a relative path, so you can use ../Code
