### ISSUE TITLE
Question: Is it possible to have multiple sed operations and commits run in one branch and MR

### ISSUE THREAD

**Issue by lovetheguitar** [asottile/all-repos#276]
Hi,

currently I have a few repositories with broken flake8 configuration (https://gitlab.com/pycqa/flake8 not available anymore)
as well as broken isort installation.

So I'd need to fix both in the same branch to have a successful pipeline in CI.

Thanks for the great tool!

**Comment by asottile** [comment]
yes, you can write an autofixer which composes autofixers
