### ISSUE TITLE
How to make PRs to many branches of one repo

### ISSUE THREAD

**Issue by radekjezdik** [asottile/all-repos#304]
So far I'm testing this tool, but I can't figure out how to update not only the master branch but also, for example, every release branch in one repository. 

Meaning: I want to make a change in a project dependency for every matching repository and all its branches that it can find and make a PR to all of them (even branches). If it allows me to filter on branch names too, e.g. only consider `release-.*` branches, that would be amazing.

I stumbled on all_braches configuration option, but it doesn't seem to do anything.

**Comment by asottile** [comment]
you would have to write your own custom push module
