### ISSUE TITLE
Question for `explains`

### ISSUE THREAD

**Issue by HeySlava** [asottile/all-repos#314]
Hello! I studied your code for all_repos.clone, and I didn't understand how _get_current_state_helper works for a folder that doesn't have a .git. This function returns [], but I expected to see None.

I simplified the example from your code as much as possible, and I got:

```
def g1():
    for _ in []:
        yield from g1()

print(list(g1()))  # return []
```
```
def g2():
    yield

print(list(g2())) # return [None]
```

How does this work?

P.S. I apologize for writing here because I haven't found a more suitable place for this.

**Comment by asottile** [comment]
check out the videos on generators (that's what those functions are)

**Comment by HeySlava** [comment]
I did, but those videos didn't answer on my question
