### ISSUE TITLE
Provide a general purpose bash command such as all-repos <cmd> or all-repos-run <cmd>

### ISSUE THREAD

**Issue by hpe-ykoehler** [asottile/all-repos#331]
Instead of creating "specific" version of all-repos cmd lines to support different tools such as grep, sed, etc.

provide a bash cmd that enable the user to define the cmd:

all-repos git status
all-repos git diff
etc.

ideally such command would have the option to filter the list of repos

all-repos -m *-proto git status
all-repos -f pom.xml git status
all-repos -g "My pattern" git status

such filter option (-m) for match repo name pattern, (-f) for has this files in it, (-g) for grep is successful in it, should also be added to all-repos-list-repos/sed/grep/find-files and other cmd as well as to make them more efficient when dealing with large quantity of repos.

**Comment by asottile** [comment]
you're looking for `xargs`

**Comment by hpe-ykoehler** [comment]
xargs would require also getting the "root" of all the repo as stored in ~/all-repos.json which would lead to dup.

Unless all-repos-list-repos can provide repo name with path.

**Comment by hpe-ykoehler** [comment]
and technically if the claims is that use xargs instead, then it void all the -grep/-find-files variant as well as one could have used xargs there as well.

It makes things a lot more readable not to have to use xargs and also can add parallel support execution with serialize output which I do not believe xargs has.

**Comment by asottile** [comment]
you're perhaps looking for `--output-paths`

the design is that common operations are commands and the rest can be achieved via xargs or custom fixers and I'm not changing it
