### ISSUE TITLE
Add support for AWS Codecommit... update summary

### ISSUE THREAD

**Issue by alexevansigg** [asottile/all-repos#332]
Would be great to have support for aws codecommit...

My project uses git-remote-codecommit to pull git repositories from aws accounts... https://github.com/aws/git-remote-codecommit

The syntax is straight forward for cloning repositories... as it uses a custom protocol and AWS SSO Profile name as the git user... the Authentication is then all managed through AWS IAM/SSO.

 eg. git clone codecommit://demo-profile@MyRepositoryName
 
 So adding support for this in your tool is likely not a huge challenge? Maybe I can have a stab at it if i had time.
 
 Anyway until then might make sense to update the Project summary to make it more obvious this plugin is github specific for now.
 
Apologies if thats already there and i missed it.
Cheers. Alex.

**Comment by asottile** [comment]
it's not github specific.  as you can see from the readme there are many pluggable sources and all you would need to do is write a source for your particular provider
