### ISSUE TITLE
Inconsistency in _check_output_dir()

### ISSUE THREAD

**Issue by asturnus** [asottile/all-repos#352]
The code in `config.py` spawns the following error:

`output_dir should only contain repos.json, repos_filtered.json, and directories`

However, on the closer inspection, the code and the error message don't seem to match up:

```python
        if not (
                contents >= REPOS_JSON_FILES and
                all(
                    os.path.isdir(os.path.join(output_dir, d))
                    for d in contents - REPOS_JSON_FILES
                )
        ):
            raise SystemExit(
                'output_dir should only contain repos.json, '
                'repos_filtered.json, and directories',
            )
```

`contents >= REPOS_JSON_FILES` will always return False unless the `.json` files are present, which contradicts the error message.

Either the logic or the error message should be changed.

**Comment by asottile** [comment]
the error message looks right to me? and the logic seems correct? are you confused maybe?

**Comment by asturnus** [comment]
I guess the source of confusion is the wording of the error message. If it clearly indicated that `output_dir` **must** contain `repos.json` and `repos_filtered.json`, there wouldn't be any confusion.

**Comment by asturnus** [comment]
Okay, I will try to explain myself more clearly. The way the error message reads to me is `output_dir` is **allowed to contain** only the mentioned json files and directories. It took some time for me, as a new user, to figure out that those json files **must** be present, and their absence is the actual error. Since it cost some time, my assumption is that other people also might have had a similar issue, hence the ticket. Please try to see this from a new user's perspective.

**Comment by asottile** [comment]
those files are created by the tool. if you got into a state without them then you've messed with the internal files somehow

you shouldn't ever need to create those files

**Comment by asturnus** [comment]
Sure, but I didn't know that I messed judging by the error message, that's my point.
