### ISSUE TITLE
Question: How to run some command in every repo?

### ISSUE THREAD

**Issue by RafaelWO** [asottile/all-repos#353]
I have basically the same question as mentioned in https://github.com/asottile/all-repos/issues/331: How can I run a specific command, e.g. `cruft update` in every repository via all-repos? But I could not comment there since the issue is locked.

I read through the answers in https://github.com/asottile/all-repos/issues/331 but apparently I am too dumb to figure out a way of doing this via `xargs`.

What I tried to far:

```
all-repos-find-files --repos -- '.cruft.json' | 
  xargs all-repos-manual -i --commit-msg "Update from template" --branch-name 'update/template' --repos
```

I hoped that with the command above I could "stop" in every repo and manually run my command. But it just went through every repo and ran `git fetch` (see partial output below)

```
***_repos-all/company/foo
$ git clone --quiet _repos-all/company/foo /tmp/tmpda6huve1
$ git remote set-url origin git@gitlab.com:company/foo.git
$ git fetch --prune --quiet
$ git checkout --quiet origin/HEAD -b all-repos_autofix_update/template
Opening an interactive shell, type `exit` to continue.
Any modifications will be committed.
$ git diff origin/HEAD --exit-code
***_repos-all/company/bar
$ git clone --quiet repos-all/company/bar /tmp/tmpl73_brv6
$ git remote set-url origin git@gitlab.com:company/bar.git
$ git fetch --prune --quiet
$ git checkout --quiet origin/HEAD -b all-repos_autofix_update/template
Opening an interactive shell, type `exit` to continue.
Any modifications will be committed.
$ git diff origin/HEAD --exit-code
```

Thank you for any advice and guidance!

**Comment by RafaelWO** [comment]
Thanks for the hint, @asottile!

As far as I see, `all-repos-manual` is [forced to be interactive](https://github.com/asottile/all-repos/blob/ba6737a399f5d6e273365ffb30805ffe6927e4a8/all_repos/manual.py#L31C5-L31C28). I guess I need to write my own autofixer if I want to run a command in every repo non-interactively, correct? Or is there something similar in this project that I missed?

**Comment by asottile** [comment]
yeah that's why it's called "manual"
