### ISSUE TITLE
Allow a "read only" mode where `push_settings` are optional

### ISSUE THREAD

**Issue by asottile** [asottile/all-repos#36]
Basically make the configuration lazily load the various parts for pushing / pulling

This would enable one to make a r/o all-repos

I guess this could just be implemented as a builtin `noop` push and then:

```json
    "push": "all_repos.push.noop",
    "push_settings": {}
```

**Comment by sloria** [comment]
Ah, was looking for something like this. Would be nice if pushing were optional. Also, a `commit_to_branch` push strategy would be nice.

**Comment by asottile** [comment]
could you elaborate on `commit_to_branch`? I believe `merge_to_master` should satisfy that -- though I need to make it understand the changes for #6

**Comment by sloria** [comment]
Yeah, disregard `commit_to_branch`. `merge_to_master` does what I was thinking of.

**Comment by sloria** [comment]
This `noop` strategy would be useful for the following workflow

1. Run an autofix with `noop` push
2. Make manual changes in the repos to fix things up if necessary
3. Commit, e.g. `all-repo-commit -m "Apply foo fix"` or `all-repo-git commit -m "Apply foo fix"`

**Comment by asottile** [comment]
Have you played well `all-repos-manual`?

**Comment by sloria** [comment]
I hadn't; that might do the trick. Looks like it requires `--repos` to be passed, though. Any way to have it just go through all the repos or just ones that match a given `grep`?

**Comment by asottile** [comment]
all the tools are meant to be composed, in this case you can use something like:

```
all-repos-manual ... --repos $(all-repos-list-repos)
all-repos-manual ... --repos $(all-repos-grep --repos ...)
all-repos-manual ... --repos $(all-repos-find-files --repos ...)
```
