### ISSUE TITLE
gitlab source

### ISSUE THREAD

**Issue by asottile** [asottile/all-repos#60]

**Comment by RonnyPfannschmidt** [comment]
im looking into getting a time allocation for doing this

**Comment by asottile** [comment]
someone expressed interest in this on stream, I believe the api is https://docs.gitlab.com/ee/api/projects.html#list-user-projects

**Comment by RonnyPfannschmidt** [comment]
atm #109 is stalled for personal reasons

**Comment by asottile** [comment]
yep no problem -- don't feel obligated <3 real life always takes precedence!

**Comment by RonnyPfannschmidt** [comment]
thanks, i don't feel obligated, but i do consider it my duty to at least inform of the state ^^

**Comment by Ericwonne** [comment]
Is this thread still updated? i was think if it's possible to clone from my company gitlab org site, however, it came up with error:

> Traceback (most recent call last):
  File "~/envs/python3_venv/bin/all-repos-clone", line 8, in <module>
    sys.exit(main())
  File "~/envs/python3_venv/lib/python3.8/site-packages/all_repos/clone.py", line 106, in main
    config = load_config(args.config_filename)
  File "~/envs/python3_venv/lib/python3.8/site-packages/all_repos/config.py", line 55, in load_config
    source_module: Any = __import__(contents['source'], fromlist=['__trash'])
ValueError: Empty module name

with below all-repos.json:

> {
    "output_dir": "output",
    "source": "",
    "source_settings":  {
        "api_key": "encrypted_content",
        "username": "Chilvery",
        "org": "www.encrypted.com"
    }
}

**Comment by RonnyPfannschmidt** [comment]
the part i needed was fixed (with the gitlab org source)

**Comment by rgarrigue** [comment]
A decent alternative https://github.com/ezbz/gitlabber

**Comment by falkben** [comment]
I'm getting a 403 Forbidden error code when running the all-repos sed command against an internal gitlab org. It creates the branch and pushes the changes, but doesn't seem to have permissions to create the merge request. Just wondering if this is known, or if I might have something misconfigured?

**Comment by falkben** [comment]
I figured out the source of my error. I needed the `api` scope in order to open Merge Requests in a group namespace that I belong to. The scope description indicates this: 

> Grants complete read/write access to the API, including all **groups** and **projects**, the container registry, and the package registry.

It's a bit unfortunate the scopes aren't a bit more fine grained.  It might be worth mentioning on the readme? If you agree, I can open a MR.
