### ISSUE TITLE
fork using target for pull requests

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/all-repos#63]
i noticed that there is no setup around shipping pull requests for fixes using an own fork

**Comment by asottile** [comment]
I believe you're looking for the `fork` option of github_pull_request: https://github.com/asottile/all-repos#all_repospushgithub_pull_request

**Comment by RonnyPfannschmidt** [comment]
@asottile does this create a new fork or does it use a owned fork?

**Comment by asottile** [comment]
Create if it does not exist, otherwise reuse existing personal fork

**Comment by asottile** [comment]
(fork is an idempotent operation in the github api)

**Comment by RonnyPfannschmidt** [comment]
closing as misunderstood by me

**Comment by RonnyPfannschmidt** [comment]
@asottile
