### ISSUE TITLE
fork pull request seems to missconfigure target at first glance

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/all-repos#64]
https://github.com/asottile/all-repos/blob/9eef439b440cb88fc46c18dd2e4f4e81ecf848d6/all_repos/push/github_pull_request.py#L30-L36

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell the wrong remote is used and the wrong head is used

**Comment by asottile** [comment]
I've used this before to open PRs with deadsnakes-issues-bot so I'm pretty sure it works :)

Note that a "fork" remote is created and then pushed to

**Comment by RonnyPfannschmidt** [comment]
@asottile then the code in question seems to be extra noise and might need a sweep, initially reading it certainly got me confused at first

**Comment by RonnyPfannschmidt** [comment]
upon rereading with focus on the implementation details you described its clear that the `head` variable is unused and the rest is indeed correct

**Comment by asottile** [comment]
#39 may clear it up? There's two modes that need handling here: fork and not

**Comment by asottile** [comment]
It's used on line 45

**Comment by RonnyPfannschmidt** [comment]
closing as misunderstood by me as well, happy monday :question:

**Comment by asottile** [comment]
<3 thanks for the issue nonetheless!

**Comment by RonnyPfannschmidt** [comment]
@asottile im contemplating giving the variables a more detailed name ^^
