### ISSUE TITLE
merge_to_master: Add setting to allow fast-forward merge

### ISSUE THREAD

**Issue by sloria** [asottile/all-repos#73]
Currently, `merge_to_master` forces a merge commit by passing `--no-ff`. I would prefer to do a fast-forward merge when doing autofixes.

It would be nice to have this behavior be configurable. Something like:

```json
   "push_settings": {
        "fast_forward": true
    }
```

**Comment by asottile** [comment]
sg2m, probably something like

```python
ff_flag = '--ff-only' if settings.fast_forward else '--no-ff'
```

You'd do this by adding a `fast_forward: bool = False` to `merge_to_master.Settings` type

**Comment by asottile** [comment]
code hint: https://github.com/asottile/all-repos/blob/ac58af15584429923a44680dad573d4bff245bcf/all_repos/push/merge_to_master.py#L12-L14

You'd switch from `collections.namedtuple` to `typing.NamedTuple` to implement this
