### ISSUE TITLE
Support "two-phase autofix"

### ISSUE THREAD

**Issue by sloria** [asottile/all-repos#78]
Currently, the autofix workflow requires that autofixing, merging, and pushing happen all in one step. This makes changes hard to reverse after everything is pushed.

It would be great if autofix happened in two phases (with separate commands): fixing then pushing.

1. Run an autofixer that commits and merges to master.
2. Manually verify that everything looks peachy.
3. Run a command to push all the repos (`all-repos-push`?).

**Comment by asottile** [comment]
I believe you're looking for the `--interactive` option that's present on all fixers

**Comment by asottile** [comment]
that or `--dry-run`

**Comment by sloria** [comment]
Yeah, I do use `--dry-run`, but that only allows me to review the combined diffs. I'd also like to review that the git steps happened as planned.

**Comment by asottile** [comment]
Try out `--interactive` -- I think it fits the bill for what you want

**Comment by asottile** [comment]
What is there to review at the merge / push stage that isn't available at the diff stage?

**Comment by sloria** [comment]
To be clear, this is what I'm imagining:

As a pre-requisite, we'd need some way to disable the push step after merging.

```json
{
    "push": "all_repos.push.merge_to_master",
    "push_settings": {"fast_forward": true, "push": false}
}
```

Then I'd run an autofixer.

```
all-repos-sed ...
```

Then I'd go into each repo and verify that the merge to master looks good. I may amend the commit with more changes.

When all look good, I can push everything up:

```
all-repos-push
```

**Comment by sloria** [comment]
> What is there to review at the merge / push stage that isn't available at the diff stage?

I would like to review that the commit message is what I expect. I also may want to amend to the commit with some related changes (that are repo-specific).

**Comment by asottile** [comment]
I understand what you're asking for, but I don't understand _why_ ;)

The internals would need a full rewrite to support that as all fixes are done in a temporary directory completely separate from the clones (to avoid the potential of local modifications and so they can fetch the latest version without modifying the local directory)

**Comment by asottile** [comment]
Hmm reviewing the commit message you're kind of out of luck -- but then again you supplied it :P -- as for repository-specific changes, anything done during `--interactive`'s `s`(hell) will be committed so I think that's already covered

**Comment by sloria** [comment]
> but then again you supplied it

...unless I'm using an autofixer I didn't write (which is how I found #77). Perhaps I should just make a practice out of passing `--msg`.

> --interactive's s(hell) 

Ah, I was wondering what `s` meant. I hadn't tried that. I think that will meet 99% of my use case, so I'll close this.

**Comment by sloria** [comment]
Thanks for the guidance!

**Comment by asottile** [comment]
that's fair, for the commit message you can see it during `--dry-run` as well
