### ISSUE TITLE
Syncing forks

### ISSUE THREAD

**Issue by mitzkia** [asottile/all-repos#89]
After I have cloned my repositories and there are some forks I would like to syncing them with upstream.
As I see after the cloning the remote is not set (checking with `git remote -v`). 
Is it my task to add remote repository with `git remote add [upstream] [git-url]` in my forks, or can it be automated with `all-repos`?

My usual workflow is (maybe not the best):
1, clone my fork
2, add upstream repository as a remote
3, sync with upstream (`git fetch --all`, `git merge upstream/master`, `git push origin master`)
4, create my topic branch + add code + create a PR from it 

If the step 4 does not take a short time I would like to sync/rebase my topic branch with the master periodically. 
I have seen the push-module maybe it could help me in creating a PR, but will it help in syncing?

So my questions:
1, can `all-repos-clone` automatically add repository from which I forked from as a remote? or is it a users task?
2, can `all-repos` help me to sync master (or other branches) from time to time with upstream?

Thank you

**Comment by asottile** [comment]
(1) it's not really the intent, but I'm sure you could write a little script which makes it happen.  `all-repos` provides a few building blocks intended to help make automating tasks like this easier.

(2) in this case you can probably leverage `all-repos-list-repos` plus a little bit of `xargs` magic  -- the tough part here is going to be figuring out the upstream -- it looks like the api that the `github` source currently uses [doesn't expose this data at all](https://developer.github.com/v3/repos/#list-user-repositories) so you'd have to make a subsequent api call yourself to [this api](https://developer.github.com/v3/repos/#get) to find if it's a fork and what the upstream is

---

that said, I've never seen the benefit of syncing forks myself, I usually use this workflow instead:

1. clone the original
1. make topic back from `origin/master`
1. [idempotent fork](https://github.com/asottile/scratch/blob/master/python/git-github-fork) (adds remote as `$username`)
1. `git push $username HEAD` (make a PR)

**Comment by mitzkia** [comment]
Thank you for your answer. Soon will check your suggestion. 
Sorry but the yet understand I which step do you sync with upstream (in your case)? 
So lets imagine you are in same commit with the upstream, you did your code change + made the PR. 
After time has passed your fork will be behind the upstream. How do you sync with upstream in this case. 
Sorry maybe this answer is in the details in your workflow (not yet tried it).
Thanks. 
I hope at the end I can switch to `all-repos` :)

**Comment by asottile** [comment]
I tend not to sync to upstreams at all 🤷‍♂️ -- by cloning the original (and `git fetch --all`) I'm always checking out from fresh master

that said, it should be possible to leverage parts of `all-repos` to accomplish what you want, let me know if you'd like some pointers on how to accomplish that :)

**Comment by mitzkia** [comment]
Oh, I see: you clone the original  :) 
I will dig into this topic (also try your suggestion) and later I will share my findings.
Thanks a lot.

**Comment by mitzkia** [comment]
My first finding related to querying/setting parent repo url (if the repo is a fork), (sorry if you already know this technique) (I know you said that this is not the intent here.., but maybe there is a small chance :) )
1, With using GitHub API v3 there is flag for each repo (if it is a fork or not): 'fork'
2, If this flag is `true` we can move one step forward: execute a new query for this repo -> and there we can find missing information related to upstream

An example with my repos:
Here you can check my repos: https://api.github.com/users/mitzkia/repos
The first repo in this list is a fork from atom/atom ('fork': true)
The needed step is: check properties for this repo: https://api.github.com/repos/mitzkia/atom
And there we can find values which we needed: parent.git_url, parent.ssh_url

Maybe it helps.

**Comment by mitzkia** [comment]
Sorry, just realized you wrote the same :)

**Comment by mitzkia** [comment]
So finally I should make a manual step here to add my upstream repo. Ok.
The other thing is not related to this issue. I will try your workflow, maybe it also fits for me,

**Comment by mitzkia** [comment]
I think I have no other question right now to this topic -> so close.

**Comment by johndpope** [comment]
so from this gist https://gist.github.com/CristinaSolana/1885435

these are the commands to sync a remote fork back to local fork - 
I will get around to making this a full script one day.....

```
git clone https://github.com/pandas-dev/pandas (REPO_URL)
cd pandas
git remote add upstream https://github.com/pandas-dev/pandas.git ( parent.git_url)
git fetch upstream
git checkout master
git pull upstream master
git add -A
git commit -m "Sync upstream master with master branch"
git push origin master
```
